# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='组名')),
            ],
        ),
        migrations.CreateModel(
            name='AnsibleHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='主机名或ip')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.AnsibleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='CpuMonit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cpu使用率')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('time_stamp', models.BigIntegerField(verbose_name='毫秒时间戳')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=32, verbose_name='设备名')),
                ('disk_type', models.CharField(max_length=32, verbose_name='硬盘类型')),
                ('disk_size', models.CharField(max_length=32, verbose_name='硬盘大小')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('cpu', models.CharField(max_length=32, verbose_name='CPU')),
                ('memory', models.CharField(max_length=32, verbose_name='内存')),
                ('os', models.CharField(default='CentOS', max_length=32, verbose_name='操作系统')),
                ('status', models.BooleanField(default=True, verbose_name='是否在线')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.AnsibleHost')),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_info', models.CharField(max_length=32, verbose_name='CPU信息')),
                ('kernel', models.CharField(max_length=32, verbose_name='内核名称')),
                ('sn', models.CharField(max_length=128, verbose_name='序列号')),
                ('os_version', models.CharField(max_length=32, verbose_name='操作系统版本')),
                ('message', models.TextField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.Host')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryMonit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cur_mem', models.IntegerField(verbose_name='当前使用内存')),
                ('mem_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='内存使用率')),
                ('mem_all', models.IntegerField(verbose_name='最大内存')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('time_stamp', models.BigIntegerField(verbose_name='毫秒时间戳')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=32, verbose_name='网卡名称')),
                ('ipaddr', models.CharField(max_length=32, verbose_name='IP地址')),
                ('netmask', models.CharField(max_length=64, verbose_name='子网掩码')),
                ('network', models.CharField(max_length=32, verbose_name='网络地址')),
                ('mac_addr', models.CharField(max_length=32, verbose_name='MAC地址')),
                ('bandwidth', models.CharField(blank=True, max_length=32, null=True, verbose_name='网卡速率')),
                ('active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房/地区')),
                ('message', models.TextField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Host')),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Host'),
        ),
        migrations.AddField(
            model_name='cpumonit',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Host'),
        ),
    ]
