# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='组名')),
            ],
        ),
        migrations.CreateModel(
            name='AnsibleHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, verbose_name='主机名或ip')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.AnsibleGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='memorymonit',
            name='cur_mem',
            field=models.IntegerField(verbose_name='当前使用内存'),
        ),
        migrations.AlterField(
            model_name='memorymonit',
            name='mem_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='内存使用率'),
        ),
    ]
